---
schema_version: "1.0.0"
last_updated: "2025-06-28"
type: "configuration_schema"
maintainer: "PlotWeaver Team"

config_schema:
  project:
    name:
      type: "string"
      required: true
      validation: "^[a-zA-Z0-9_-]+$"
    description:
      type: "string"
      required: true
      max_length: 1000
    genre:
      type: "string"
      required: true
      enum:
        - "fantasy"
        - "science_fiction"
        - "mystery"
        - "literary"
        - "historical"
    target_length:
      type: "integer"
      required: true
      min: 20000
      max: 200000
    language:
      type: "string"
      default: "en"
      enum: ["en", "es", "fr"]
  
  git:
    repo_url:
      type: "string"
      required: true
      validation: "^https://github.com/.+/.+$"
    auth_token:
      type: "string"
      required: true
      secret: true
      validation: "^gh[ps]_[a-zA-Z0-9]{36}$"
    branch:
      type: "string"
      default: "main"
  
  generation:
    model:
      type: "string"
      required: true
      enum:
        - "gpt-4"
        - "gpt-4-turbo"
        - "claude-3-opus"
        - "claude-3-sonnet"
        - "claude-3-haiku"
        - "anthropic/claude-3-opus"
        - "anthropic/claude-3-sonnet"
        - "anthropic/claude-3-haiku"
    temperature:
      type: "float"
      required: true
      min: 0.0
      max: 1.0
      default: 0.7
    max_tokens:
      type: "integer"
      required: true
      min: 100
      max: 4000
      default: 2000
    stop_sequences:
      type: "array"
      items:
        type: "string"
      default: []
  
  structure:
    root_dir:
      type: "string"
      required: true
      validation: "^/[a-zA-Z0-9/_-]+$"
    content_dir:
      type: "string"
      required: true
      relative_to: "root_dir"
    characters_dir:
      type: "string"
      required: true
      relative_to: "root_dir"
    plot_dir:
      type: "string"
      required: true
      relative_to: "root_dir"

environment_variables:
  PLOTWEAVER_ENV:
    required: true
    enum: ["development", "staging", "production"]
  OPENROUTER_API_KEY:
    required: true
    secret: true
  GITHUB_TOKEN:
    required: true
    secret: true

file_formats:
  yaml:
    character_profiles:
      path: "characters/*.yaml"
      schema: "character_schema"
    plot_outlines:
      path: "plot/*.yaml"
      schema: "plot_schema"
    concept_data:
      path: "plot/concept.yaml"
      schema: "concept_schema"
    scene_metadata:
      path: "content/chapters/*/scene-*-metadata.yaml"
      schema: "scene_metadata_schema"
    prompts:
      path: "prompts/**/*.yaml"
      schema: "prompt_schema"
  
  markdown:
    scene_content:
      path: "content/chapters/*/scene-*.md"
      frontmatter: true
      schema: "scene_content_schema"
    documentation:
      path: "*.md"
      frontmatter: false

validation_rules:
  project_name:
    - "must be unique in organization"
    - "lowercase alphanumeric with hyphens"
    - "max length 64 characters"
  
  auth_token:
    - "must be valid GitHub token"
    - "must have repo scope"
    - "must not be expired"
  
  directories:
    - "must exist before initialization"
    - "must be writable by process"
    - "must not contain spaces"

defaults:
  project:
    language: "en"
    branch: "main"
    temperature: 0.7
    max_tokens: 2000
  
  directories:
    content: "./content"
    characters: "./characters"
    plot: "./plot"
    prompts: "./prompts"

upgrade_policies:
  config_version:
    auto_upgrade: true
    backup: true
    notify_user: true
  
  schema_version:
    auto_upgrade: false
    backup: true
    notify_user: true
