name: Process GitHub Issue

on:
  issues:
    types: [opened, closed, edited]

permissions:
  contents: write
  issues: read

jobs:
  process-issue:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Process issue
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        EVENT_TYPE: ${{ github.event.action }}
      run: |
        python scripts/process-issue.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Auto-generate documentation for issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}
          
          🤖 Generated with [Claude Code](https://claude.ai/code)
          
          Co-Authored-By: Claude <noreply@anthropic.com>"
          git push
        else
          echo "No changes to commit"
        fi